#!/usr/bin/env python2.4
# -*- coding: utf-8 -*-
#  Copyright (C) 2007 Jacek Śliwerski (rzyjontko)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; version 2.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  

LANGUAGES = {
    'af' : u'Afrikaans',
    'ar' : u'العربية',
    'az' : u'Azərbaycan',
    'be' : u'Беларуская',
    'be_latin' : u'Biełaruskaja',
    'bg' : u'Български',
    'bn' : u'বাংলা',
    'br' : u'Brezhoneg',
    'bs' : u'Bosanski',
    'ca' : u'Català',
    'cs' : u'Čeština',
    'csb' : u'Kaszëbsczi',
    'cy' : u'Cymraeg',
    'da' : u'Dansk',
    'de' : u'Deutsch',
    'el' : u'Ελληνικά',
    'en' : u'English',
    'en_gb' : u'English',
    'eo' : u'Esperanto',
    'es' : u'Español',
    'et' : u'Eesti',
    'eu' : u'Euskara',
    'fa' : u'فارسی',
    'fi' : u'Suomi',
    'fo' : u'Føroyskt',
    'fr' : u'Français',
    'fy' : u'Frysk',
    'ga' : u'Gaeilge',
    'gl' : u'Galego',
    'ha' : u'هَوُسَ',
    'he' : u'‫עברית‬',
    'hi' : u'हिन्दी',
    'hr' : u'Hrvatski',
    'hsb' : u'Hornjoserbsce',
    'hu' : u'Magyar',
    'id' : u'Bahasa Indonesia',
    'is' : u'Íslenska',
    'it' : u'Italiano',
    'ja' : u'日本語',
    'ka' : u'ქართული',
    'kk' : u'Қазақша',
    'km' : u'ភាសាខ្មែរ',
    'ko' : u'한국어',
    'ku' : u'Kurdî/كوردی',
    'lb' : u'Lëtzebuergesch',
    'lo' : u'ລາວ',
    'lt' : u'Lietuvių',
    'lv' : u'Latviešu',
    'mg' : u'Malagasy',
    'mi' : u'Māori',
    'mk' : u'Македонски',
    'mn' : u'Монгол',
    'ms' : u'Bahasa Melayu',
    'mt' : u'bil-Malti',
    'nb' : u'Norsk bokmål',
    'nds' : u'Plattdüütsch',
    'ne' : u'नेपाली',
    'nl' : u'Nederlands',
    'nn' : u'Norsk nynorsk',
    'oc' : u'Occitan',
    'pa' : u'ਪਜਾਬੀ/पंजाबी/پنجابي',
    'pl' : u'Polski',
    'pt' : u'Português',
    'pt_br' : u'Português',
    'ro' : u'Română',
    'ru' : u'Руccкий',
    'rw' : u'Ikinyarwanda',
    'se' : u'Sámegiella',
    'sk' : u'Slovenčina',
    'sl' : u'Slovenščina',
    'sq' : u'Shqip',
    'sr' : u'Српски',
    'sr_latn' : u'Srpski',
    'ss' : u'SiSwati',
    'sv' : u'Svenska',
    'ta' : u'தமிழ்',
    'te' : u'తెలుగు',
    'tg' : u'Тоҷикӣ',
    'th' : u'ไทย',
    'tr' : u'Türkçe',
    'tt' : u'Tatarça/Татарча',
    'uk' : u'Українська',
    'uz' : u'Ўзбек',
    'ven' : u'Tshivenda',
    'vi' : u'Tiếng Việt',
    'wa' : u'Walon',
    'xh' : u'isiXhosa',
    'zh_cn' : u'古文/文言文',
    'zh_hk' : u'古文/文言文',
    'zh_tw' : u'古文/文言文',
    'zu' : u'isiZulu'
    }

